### ISSUE TITLE
Checking broken links in documentation

### ISSUE THREAD

**Issue by zarak** [mini-kep/documentation#2]
There is a post [here](https://github.com/mkdocs/mkdocs/issues/738#issuecomment-277236506) about validating external links using [awesome_bot](https://github.com/dkhamsing/awesome_bot). Would something like this be useful?

**Comment by epogrebnyak** [comment]
I like that <https://github.com/dkhamsing/awesome_bot> has travis in mind, but it is written in Ruby. 
<https://github.com/alecxe/broken-links-checker> seems to be a small python alternative using spyder.

**Comment by epogrebnyak** [comment]
For now, let's not do any atomatic checks on the links - there seems no good ready solution.
